version: "3.8"
services:
  mongo:
    image: mongo
    volumes:
      - ./docker/mongodb/init:/docker-entrypoint-initdb.d
      - ./docker/mongodb/db:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: admin
    ports:
      - "27017:27017"
  mongo-express:
    depends_on:
      - mongo
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
  react:
    build:
      context: ./
      dockerfile: Dockerfile
    image: jp3pe/plane/react
    container_name: plane-react
    ports:
      - "8007:8007"
  node:
    build:
      context: ./server
      dockerfile: Dockerfile
    depends_on:
      - mongo
      - mongo-express
    image: jp3pe/plane/node
    container_name: plane-node
    ports:
      - "8008:8008"